project:
  type: website
  output-dir: docs

website:
  title: "Cody and Quang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resources.qmd
        text: Resources
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



